@host= http://localhost:5001/v1/api/admin/banner

@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWxfaWQiOiJ0ZXN0QHlvcG1haWwuY29tIiwib3JnX2lkIjoiQUkwMDAwMSIsImlhdCI6MTY5NjAwMDk3NCwiZXhwIjoxNzM5MjAwOTc0fQ.bdgVi2oVc7lUQuBbgyJ5gPa0rtHiYoULAbWwHoeOte8


@token2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiZW1haWxfaWQiOiJzdWNrMUB5b3BtYWlsLmNvbSIsIm9yZ19pZCI6IkFJMDAwMDIiLCJpYXQiOjE2OTQyNjE3NzksImV4cCI6MTczNzQ2MTc3OX0.3_EYQJrbEC3zYh0g97JmGGVkdu61ewjfPUeLtIL9Wc8



POST {{host}}/create-banner
Content-Type: application/json
Authorization: Bearer {{token}}

{
  
  "image_url":["http://newaffdfgsfsfditem.com","http://newaffdfgsfsfdite213123m.com"],
  "status":false,
  "type":"external_link",
  "type_id":"sdfnasdkfnaksdfabsdf",
  "type_name":""
    
}

###
GET {{host}}/get-all-banner?page=1&limit=20&search=
Content-Type: application/json
Authorization: Bearer {{token}}
 
###
GET {{host}}/get-banner-by-id?banner_id=6
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{host}}/update-banner
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "banner_id":"1",
   "image_url":" 234234234aswitem.com",
  "status":false,
  "type_id":"32",
  "type":"category"
   
}
###
POST {{host}}/delete-banner
Content-Type: application/json
Authorization: Bearer {{token}}

{
 "banner_id":"1"
}
 